/**
 * Diff Writer Utility
 * Applies unified diffs with scope-based validation
 */

import type { ScopeLevel } from "../agent/types";

interface DiffValidationResult {
  valid: boolean;
  errors: string[];
  allowedPaths: string[];
}

interface ApplyDiffResult {
  success: boolean;
  filesChanged: string[];
  errors: string[];
}

// Scope-based path restrictions
const SCOPE_RULES: Record<ScopeLevel, string[]> = {
  DATA_ONLY: [
    "src/store/**/*.ts",
    "src/types/**/*.ts",
    "src/lib/schema.ts",
  ],
  UI_SAFE: [
    "src/components/**/*.tsx",
    "src/components/**/*.ts",
    "src/features/**/*.tsx",
    "src/features/**/*.ts",
    "src/**/*.css",
  ],
  LOGIC_STRICT: [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.js",
    "src/**/*.jsx",
  ],
};

// Paths that should NEVER be modified by the agent
const FORBIDDEN_PATHS = [
  "package.json",
  "package-lock.json",
  "node_modules/**",
  ".git/**",
  "dist/**",
  "build/**",
  "vite.config.*",
  "tsconfig.json",
];

/**
 * Validate that a diff conforms to scope restrictions
 */
export function validateDiff(
  diff: string,
  scope: ScopeLevel
): DiffValidationResult {
  const errors: string[] = [];
  const allowedPaths = SCOPE_RULES[scope];
  
  // Parse file paths from unified diff
  const filePathRegex = /^(?:---|\+\+\+)\s+([^\s]+)/gm;
  const matches = [...diff.matchAll(filePathRegex)];
  const filePaths = matches
    .map((m) => m[1])
    .filter((p) => p !== "/dev/null")
    .map((p) => p.replace(/^[ab]\//, "")); // Remove a/ or b/ prefix
  
  // Check against forbidden paths
  for (const path of filePaths) {
    for (const forbidden of FORBIDDEN_PATHS) {
      if (matchGlob(path, forbidden)) {
        errors.push(`Path ${path} is forbidden (matches ${forbidden})`);
      }
    }
  }
  
  // Check against scope rules (only if in restricted scopes)
  if (scope !== "LOGIC_STRICT") {
    for (const path of filePaths) {
      const allowed = allowedPaths.some((pattern) => matchGlob(path, pattern));
      if (!allowed) {
        errors.push(
          `Path ${path} not allowed for scope ${scope}. Allowed: ${allowedPaths.join(", ")}`
        );
      }
    }
  }
  
  return {
    valid: errors.length === 0,
    errors,
    allowedPaths,
  };
}

/**
 * Parse and apply a unified diff
 * NOTE: This is a simplified implementation. In production, use a library like 'diff' or 'unified'
 */
export async function applyDiff(
  diff: string,
  scope: ScopeLevel,
  workspaceRoot: string = "/"
): Promise<ApplyDiffResult> {
  const validation = validateDiff(diff, scope);
  
  if (!validation.valid) {
    return {
      success: false,
      filesChanged: [],
      errors: validation.errors,
    };
  }
  
  // For now, return a mock success
  // TODO: Implement actual diff application using:
  // 1. Parse the unified diff format
  // 2. Read the target file
  // 3. Apply the hunks
  // 4. Write the modified file
  // OR use a library like 'apply-patch' or 'diff'
  
  const filesChanged = extractFilePaths(diff);
  
  return {
    success: true,
    filesChanged,
    errors: [],
  };
}

/**
 * Extract file paths from a unified diff
 */
function extractFilePaths(diff: string): string[] {
  const filePathRegex = /^(?:---|\+\+\+)\s+([^\s]+)/gm;
  const matches = [...diff.matchAll(filePathRegex)];
  const paths = matches
    .map((m) => m[1])
    .filter((p) => p !== "/dev/null")
    .map((p) => p.replace(/^[ab]\//, ""));
  
  // Deduplicate
  return [...new Set(paths)];
}

/**
 * Simple glob matcher (supports ** and * wildcards)
 */
function matchGlob(path: string, pattern: string): boolean {
  // Convert glob to regex
  let regex = pattern
    .replace(/\*\*/g, "___DOUBLESTAR___")
    .replace(/\*/g, "[^/]*")
    .replace(/___DOUBLESTAR___/g, ".*")
    .replace(/\?/g, ".");
  
  regex = `^${regex}$`;
  
  return new RegExp(regex).test(path);
}

/**
 * Generate a unified diff for demonstration purposes
 * In production, this would be generated by the AI or a diff tool
 */
export function generateExampleDiff(
  filePath: string,
  oldContent: string,
  newContent: string
): string {
  // Simplified diff generation
  const lines = newContent.split("\n");
  const oldLines = oldContent.split("\n");
  
  let diff = `--- a/${filePath}\n`;
  diff += `+++ b/${filePath}\n`;
  diff += `@@ -1,${oldLines.length} +1,${lines.length} @@\n`;
  
  oldLines.forEach((line) => {
    diff += `-${line}\n`;
  });
  
  lines.forEach((line) => {
    diff += `+${line}\n`;
  });
  
  return diff;
}
